version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=Qwe1234
    volumes:
      - ./local/db:/var/lib/mysql:z  
  redis:
    image: redis
    ports: 
      - 6479:6479
